# -*- mode: python ; coding: utf-8 -*-
#
# Onedir build + BUNDLE -> VoiceFlow.app. Point of reference: packaging/windows/voiceflow.spec
# (onefile .exe there; here PyInstaller needs a folder plus BUNDLE to produce an .app).
# Runs only on macOS (PyInstaller cannot cross-build a .app from Windows/Linux).

import os
import sys

block_cipher = None

ROOT = os.path.abspath(os.path.join(SPECPATH, '..', '..'))
sys.path.insert(0, ROOT)

from voiceflow.__version__ import __version__

try:
    from PyInstaller.utils.hooks import collect_submodules
except ImportError:
    def collect_submodules(name):
        return []

# pynput's darwin backend (pynput.keyboard._darwin / pynput.mouse._darwin) is built on
# pyobjc; without these frameworks collected the app imports pynput fine but crashes the
# moment it tries to install the keyboard/mouse listener.
_PYOBJC_FRAMEWORKS = ['Quartz', 'AppKit', 'ApplicationServices']
_pyobjc_hidden = []
for _framework in _PYOBJC_FRAMEWORKS:
    try:
        _pyobjc_hidden += collect_submodules(_framework)
    except Exception:
        pass

ICON_PATH = os.path.join(ROOT, 'assets', 'macos', 'icon.icns')
if not os.path.isfile(ICON_PATH):
    # Generated by packaging/macos/build.sh (iconutil) before this spec runs; falls back
    # to no icon so the spec still compiles/builds if that step was skipped.
    ICON_PATH = None

ENTITLEMENTS_FILE = os.path.join(SPECPATH, 'entitlements.plist')
if not os.path.isfile(ENTITLEMENTS_FILE):
    ENTITLEMENTS_FILE = None

a = Analysis(
    [os.path.join(ROOT, 'main.py')],
    pathex=[ROOT],
    binaries=[],
    datas=[
        (os.path.join(ROOT, 'assets', 'common'), os.path.join('assets', 'common')),
    ],
    hiddenimports=[
        'pynput.keyboard._darwin',
        'pynput.mouse._darwin',
        'PyQt6.QtCore',
        'PyQt6.QtGui',
        'PyQt6.QtWidgets',
        'anthropic',
        'requests',
        'pyaudio',
    ] + _pyobjc_hidden,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    # Windows excludes minus 'xml': voiceflow/platform/macos.py uses plistlib at
    # top level, which imports xml.parsers.expat; excluding xml crashes the app on start.
    excludes=['tkinter', 'unittest', 'pydoc'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='VoiceFlow',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch='arm64',
    codesign_identity=None,
    entitlements_file=ENTITLEMENTS_FILE,
    icon=ICON_PATH,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='VoiceFlow',
)

app = BUNDLE(
    coll,
    name='VoiceFlow.app',
    icon=ICON_PATH,
    bundle_identifier='com.mta.voiceflow',
    info_plist={
        'CFBundleIdentifier': 'com.mta.voiceflow',
        'CFBundleName': 'VoiceFlow',
        'CFBundleShortVersionString': __version__,
        'CFBundleVersion': __version__,
        'LSUIElement': True,
        'NSMicrophoneUsageDescription': (
            'VoiceFlow records your voice only while you hold the hotkey, '
            'to turn it into text.'
        ),
        'NSHighResolutionCapable': True,
        'LSMinimumSystemVersion': '13.0',
    },
)
